// Clean list of valid baseline athlete names (from subway_baseline_beforecomments.csv)
// These are the ONLY athletes that should appear in the Sub Club (story-only) section
export const BASELINE_ATHLETE_NAMES = new Set([
    "Aaron Meono", "Aaron Posey", "Aaron Staats", "Aaron Young", "Abbey Debevec", "Adam Agyemang",
    "Addison Laughlin", "Addison Papagolos", "Adel Hoglund", "Adrian Wynn", "Adriana Milanez",
    "Adrianna Runzo", "Ahkise Williams", "Aidan Andre", "Aidan Starling", "Aidan Warnock",
    "Ainsley Yates", "Alejandro Diaz Diaz", "Alejandro Jacome", "Alex Pottorff", "Alexander Luszcz",
    "Alexis Re", "Alionna Chappell", "Alivia Lilly", "Alizee Garcia Parsons", "Allie Mouch",
    "Alyssa Cadavid", "Amare Chapel", "Amari George", "Amari Powell", "Amon Gill", "Amoryan Ferguson",
    "Andie Psilopoulos", "Andre Bigham", "Andre Gonzalez", "Andrew Wright", "Andy Yang",
    "Angelique Moreno", "Ansley Murphy", "Anthony Feltrinelli", "Anthony Guglielmo", "Anthony Long",
    "Anthony McClinton", "Anthony Parker", "Anthony Toolson", "Anton Gabriel Alarcon", "Antoni Siewruk",
    "Ariel Guzman", "Arron Finott", "Arthur Chavez", "Ashanti Harvey", "Ashlyn Kahre", "Aubrey Eaton",
    "Audrey Argonish", "Audrey Taylor", "Austin P", "Autumn Perry", "Ava Rajala", "AvaClaire Collins",
    "Avion Phillips", "Azel Lunsford", "Beau Leisure", "Beckham Stirling", "Benjamin Molnau",
    "Benjamin Solano", "Berklie Ahlander", "Blake Allen", "Blane Cleaver", "Bodde Simon",
    "Braden Benton", "Braden Mounyo", "Brady Beko", "Brady Benevides", "Brady Cronkhite",
    "Brandon Alston", "Braxton Bartz", "Braxton Nixon-snell", "Brayden Evans", "Brayden Lane",
    "Brayden Torgrimson", "Braylon Hilliard", "Bre Clark", "Brenden Aenis", "Brock Montgomery",
    "Brody Morrison", "Bryan Bedolla", "Cade Ragonese", "Caden Cain", "Caedmon Dickson", "Caelyn Gunn",
    "Caio Araujo", "Caleb Weiand", "CamRen Brooks", "Camarion Ragland", "Camden Franjieh",
    "Camden Hawkins", "Cameron Rayborn", "Camren Tolbert", "Carly Hyers", "Carmello Bostwick",
    "Carson Brundige", "Carson Hein", "Casey Spencer", "Caterrin Cox", "Cavon Reid", "Ceasar Figueroa",
    "CeeJai Batten", "Celia Trotter", "Chai Dunlap", "Chandler Donaway", "Chase Birdsall",
    "Chase Hight", "Chase Schefke", "Cheyanne Whitfield", "Chiara Judis", "Chisom Onwuzurigbo",
    "Chloe Macias", "Chris Messina", "Christian Washington", "Christion Washington",
    "Christopher Cecchini", "Ciara Adu-Addo", "Cj Gaffney", "Cj Richard", "Clarens Dollin",
    "Clayton Renfrew", "Cody Birlson", "Cody Templeton", "Cole Carbone", "Cole Smither",
    "Collin Roelofs", "Collin Stockero", "Colson Knott", "Cooper Marx", "Courtney Wiltz",
    "Cymia Yourish", "Dalton Hall", "Damiyah Smith", "Daniel Atsou", "Daniel Burko", "Daniel Powell",
    "Darius Safavi-Abbassi", "David Anderson", "David Loew", "David Roberts", "Dawson Debebe",
    "Deacon Toliver", "Deja Churchill", "Demetri Bose", "Denzel Alexandre-louis", "Denzel Willingham",
    "Dequan Thompson", "Destiny Washington", "Deuce Roberson", "Deverious Abercrombie", "Devin Garcia",
    "Diego Alana", "Dillon Leacock", "Donny Birkett", "Dontarris Wesby", "Donte Lewis", "Dozie Ononye",
    "Dreshaun Johnson", "Drew Rankin", "Dylan DePriest", "Dylan Mayhew", "Dylan White",
    "Easton Sheppeard", "Ej Hargrave", "Eldridge Shelton Jr", "Elena Kossler", "Elijah Kinsler",
    "Elizabeth Garza", "Ella Luegge", "Ella Whitaker", "Elo Okpah", "Eloise Stuart",
    "Emily Havrylyshen", "Emily Jones", "Emma Eckert", "Emma Overall", "Eric Rivera", "Ernesto Garza",
    "Ethan Oceguera", "Evan Atkin", "Evan Fisher", "Evelyn Miller", "Fabian Ramirez", "Finn Rodgers",
    "Fiona Kilian", "Gabi Barrera", "Gabriel Showalter", "Gabriel Souza", "Gage Burdick",
    "Gage Burnett", "Gannon Ysais", "Gary Moore Jr", "Gavin McLean", "Gavin Thompson",
    "Gehrig Slunaker", "Gisele Tankersley", "Godwin Edeh", "Grace Booth", "Grace Conlin",
    "Grace Lynch", "Grace Rowan", "Gracie Rellin", "Greyson Ervin", "Gustavo Bravo", "Guymike Paraison",
    "Hailey Brown", "Hailey Holtz", "Haleigh Peters", "Harold Fernandez", "Hayden Westman",
    "Hayley Messer", "Helen Randolph", "Imran Okedeyi", "Isabel Seifert", "Isabella Carlson",
    "Isabella Minervini", "Isaiah Harrison", "Isaiah Johnson", "Isaiah Reveron", "Isaiah Stein",
    "Isam Banajah", "Israel Ford", "Izzy Fay", "Izzy Wilson", "Jaci Bolden", "Jack Veletanga",
    "Jackson Chirello", "Jackson Contreras", "Jackson Kamp", "Jacob Beck", "Jacob English",
    "Jacob McGhee", "Jacob Mullis", "Jada Covington", "Jada Edwards", "Jada Pride", "Jade Reese",
    "Jadon Lewis", "Jaeden Warner", "Jaiden Block", "Jake Rittman", "Jalen Mccray", "Jamar Marshall",
    "Jameer Reeder", "James Monds", "Jamie Kent", "Jamilia Duffus", "Jamir Ford", "Jan Avila",
    "Jared Hodgson", "Jared Moore", "Jarett Sabol", "Jason Barket", "Jason Campbell", "Jason Davis",
    "Jason Harris", "Jason Louiso", "Javion Lane", "Jaxson Stiner", "Jay Fuller", "Jayden Anderson",
    "Jayden Epperson", "Jayden Mieske", "Jayden Wylie", "Jaylee Ojo", "Jaylen Carter", "Jazmine Gaston",
    "Jeremi Lara", "Jeremiah Johnson", "Jeremy Gaut", "Jeremy Giesegh", "Jermari Seals",
    "Jessica Deleon", "Jessica Okorie", "Jj Jones", "Johanna Holston", "John Williams III",
    "Jonah Davis", "Jonah Young", "Jonathan Beard", "Jonathan Gonzalez", "Jonni Sanchez",
    "Jordan Booth", "Jordan Smith", "Jordan Williams", "Joseph Hasan", "Josh Davis", "Josiah Morris",
    "Jozef Palushaj", "Juan Abella", "Jude Carlton", "Julia Walaszek", "Julian Bush", "Julian Johnson",
    "Julian Stevens", "Juliana Lupercio", "Julianna Becerra", "Julie Smith", "Julius Hiley",
    "Juni Rodriguez", "Justin Gutierrez", "Justin Jubert", "Justin Simpson", "Justus Haseley",
    "Jy Edwards", "Kainen White", "Kalee Rochinski", "Kali Austerman", "Kantrel Smith", "Kate Hawley",
    "Kayden Banker", "Kayden Chick", "Kayla Alexandre", "Keegan Good", "Keith Frazier", "Kellan Hudson",
    "Kenny Pierpoint", "Kevin Duran", "Kevin Marcus", "Khalil Johnson", "Khanyla Hooten",
    "Khyair Goodwin", "Kiael Kelly", "Kierstin Ashby", "Kiya Dorroh", "Kobe Barker", "Krista Mazariegos",
    "Kyanna Creecy", "Kylan Wallace", "Kyle Durham", "Kyle Lew", "Kylee Payne", "LJ Rogers",
    "Lance Christensen Jr", "Landan Creighton", "Landon Jenkins", "Landon Lowe", "Larry Norrington",
    "Lawrence Nalls III", "LeShaun Bennett II", "Legend Geeter", "Leo Sanders", "Linsey Burke",
    "Livi Grecco", "Lloyd French", "Logan Charbonneau", "Logan Hays", "Logan Trenary", "Lucas Shaver",
    "Lukas Donahue", "Luke Montanye", "Lylian Iman", "Macy Walters", "Maddie Simmerman",
    "Mahogany Mobley", "Maia Soulis", "Majesty Lewis", "Makailum Castile", "Makenna Ching",
    "Malachi Butler", "Malachi Grier", "Malik Blunt", "Malorie Byrne", "Marcus Young", "Mariana Valdez",
    "Markee Moorer jr", "Marquis Bates", "Mason Ellis", "Mason Kleinsmith", "Mateo Rincon",
    "Matthew Graham", "Matthew Scott", "Matthew Thissell", "Matthews Rocha", "Matty Ryan", "Max Penrod",
    "McKinnon Howard", "Melina Schrader", "Mia Cheatham", "Mia Tribul", "Micah Blair",
    "Michael Anthony Henderson", "Michael Barretto", "Michael Boucher", "Michael Brescia III",
    "Michael Dziadula", "Michael Fayiah", "Michael McAleavy", "Mitchel Szymczak", "Molly Cravens",
    "Morgan Williams", "Murphy Brooks", "Myles Walden", "Nahshawn Keith", "Nathan DeLaughter",
    "Nathan Natoli", "Nathan Patterson", "Nathaniel Thompson", "Nayo Lear", "Naziah Rice", "Nebi Young",
    "Nehemiah Stephenson", "Nevaeh Campbell", "Nia Bridgeforth", "Nicholas Cenek",
    "Nicholas Weatherford", "Nino Betances", "Nizaiah Carr", "Noah Fichter", "Noah Wilson",
    "Nolan Litkowiec", "Nyir Jones", "Octavio Singh", "Olivia Reeves", "Olivia Salmon", "Owen Thomson",
    "Pablo Lesarri", "Paeton Kringel", "Patryck Brooks", "Paul Ramseur", "Peter Detwiler",
    "Peyton Greenwood", "Peyton Stevenson", "Preston Zumwalt", "RJ Edwards", "RJ Stephens",
    "Rafael Antonio Jr", "Rafael Urena", "Rajer Gurode", "Raymond Baka", "Reagan Jones", "Reginald Alls",
    "Riley Cassiday", "Riley Johnson", "Robbie Fisher", "Roderick Mccoy jr", "Ronaldo Barnett",
    "Roy Price", "Ryan Reese", "Rylee Simoneaux", "Ryleigh Garis", "Sam Bradbury", "Sam Kromberg",
    "Sania Dearing", "Sarah Gordon", "Sarah Moite", "Saul Rios", "Sean Robertson", "Seven Warren",
    "Shadrach Nvodjo", "Shamus Gallo", "Shatarius Williams", "Shauna Gamble", "Skye Gaudio",
    "Skylar Strickland", "Sowande Mcwhite", "Spencer Cox", "Spencer Freer", "Sydney Peal",
    "Sydney Vitangcol", "Syncere Safeeullah", "TJ Williams", "Taelen Laird", "Taliya Spurlock",
    "Tanner Sheffert", "Tara Earnheart", "Taylor Jackson", "Taylor Jenkins", "TaylorLee Goebel",
    "Tesia Thomas", "Tevin Dietz", "Thalia Benoit", "Thomas Perez", "Tigran Ceesay", "Tinley Lucas",
    "Torrean Thornton", "Tramiya Batts", "Travion Woods", "Trevor Allen jr", "Trevor Bywater",
    "Trevquan Gary", "Trey Flood", "Ty Beck", "Ty Kauserud", "Ty Long", "Tyah Charlton", "Tyler Slone",
    "Tymir Jones", "Tyquan Harney", "Tyree Fleming", "Victory Godah", "Will Clemens", "Will Ostermeyer",
    "William Kemper", "Xavier Marshall", "Yarnell Smithjr", "Yasmine Morgan", "Zachary Knapp",
    "Zachary Mylenek", "Zack Peters", "Zion Howell", "Zion Lawson", "Zion Omotesa"
]);

// Helper to check if an athlete name is in the baseline list
export const isBaselineAthlete = (name: string): boolean => {
    return BASELINE_ATHLETE_NAMES.has(name);
};
